### ISSUE TITLE
似乎出现了在线人数检测的BUG

### ISSUE THREAD

**Issue by ESRFT** [SereinDev/Serein#112]
![屏幕截图 2024-08-11 015548](https://github.com/user-attachments/assets/b4b9ec31-5662-41e1-b735-9e50a1804817)
如图（希望我的操作正确，图片能够正常被您看到），我使用了两个serein，并使用了QQ机器人，热备份，fpc假人等插件。但它们似乎出现了一些问题：不存在假人挂载的创造服被错误的识别了在线9人。以下是更多的附图，很抱歉这是我第一次写反馈，需要任何更多的信息或更精确的状态烦请向我提出更多。
![屏幕截图 2024-08-11 020507](https://github.com/user-attachments/assets/38e19d86-f2d5-4ea3-b800-ba8f78b6cd44)
![屏幕截图 2024-08-11 020615](https://github.com/user-attachments/assets/a34a6cb7-ba6d-4787-89f2-fc8ab4ee3180)
![屏幕截图 2024-08-11 020656](https://github.com/user-attachments/assets/d8ec6f44-28aa-4725-a687-5db8ce541578)
![屏幕截图 2024-08-11 020738](https://github.com/user-attachments/assets/e15bf7eb-60e3-4e31-9be1-1a6496bf20cf)

**Comment by Zaitonn** [comment]
检查`设置-服务器-端口`是否与`server.properties`中的ipv4端口一致

有可能是你两个serein设置了相同的端口

>[!TIP]
>**不推荐**在同一个文件夹下使用同一个Serein启动不同的服务器（v1.x.x），若要管理多个服务器建议将Serein文件夹复制多份隔离后分别设置并启动

**Comment by ESRFT** [comment]
感谢，经检查，是在设置时使用了同样的端口导致的，修改后恢复正常。
