### ISSUE TITLE
BUG反馈 js插件创建http服务重载端口占用

### ISSUE THREAD

**Issue by Chlna6666** [SereinDev/Serein#113]
### 当前使用的Serein版本

2.0.0.0

### 你的预期

重载或者禁用后端口

### 实际上的反应

端口被system进程占用
![QQ20241211-230155](https://github.com/user-attachments/assets/17dac77e-ad8b-4626-bb3c-04cb12d2ce28)

**Comment by Zaitonn** [comment]
应该是插件问题 麻烦提供一下js源码或链接

**Comment by Chlna6666** [comment]
var HttpListener = importNamespace('System.Net').HttpListener;
var Encoding = importNamespace('System.Text').Encoding;
var IO = importNamespace('System.IO');
var File = IO.File;
var Directory = IO.Directory;

if (!HttpListener.IsSupported) {
    throw new Error("当前系统不支持 HttpListener");
}

// 默认配置
let config = {
    auth: [""],
    port: 61545,
};

// 配置文件路径
const CONFIG_DIR = 'Serein/plugins/BackupJS';
const CONFIG_FILE = `${CONFIG_DIR}/config.json`;

// 生成随机密钥
function generateRandomKey(length = 12) {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    return Array.from({ length }, () => chars.charAt(Math.floor(Math.random() * chars.length))).join('');
}

// 加载或创建配置文件
function loadConfig() {
    if (Directory.Exists(CONFIG_DIR) && File.Exists(CONFIG_FILE)) {
        try {
            const loadedConfig = JSON.parse(File.ReadAllText(CONFIG_FILE));
            if (!loadedConfig.auth || !loadedConfig.auth[0]) {
                loadedConfig.auth = [generateRandomKey()];
                saveConfig(loadedConfig);
                serein.console.warn(`AuthKey 为空，已生成随机密钥：${loadedConfig.auth[0]}`);
            }
            return loadedConfig;
        } catch (e) {
            throw new Error(`读取配置文件时出现问题：${e.message}`);
        }
    } else {
        Directory.CreateDirectory(CONFIG_DIR);
        config.auth = [generateRandomKey()];
        saveConfig(config);
        serein.console.warn("配置文件不存在，已重新创建默认配置");
        serein.console.warn(`随机生成的 AuthKey 为：${config.auth[0]}`);
        return config;
    }
}

// 保存配置文件
function saveConfig(config) {
    File.WriteAllText(CONFIG_FILE, JSON.stringify(config, null, 4));
}

// 加载配置
config = loadConfig();

// 启动监听器
let listener = new HttpListener();
listener.Prefixes.Add(`http://127.0.0.1:${config.port}/serein/`);
try {
    listener.Start();
    serein.console.log(`服务已启动，正在监听 http://127.0.0.1:${config.port}/serein/`);
    startListener();
} catch (e) {
    throw new Error(`无法启动监听器：${e.message}`);
    listener.Close();
}

// 主监听逻辑
function startListener() {
    setTimeout(() => {
        try {
            while (listener.IsListening) {
                let context = listener.GetContext();
                serein.console.log(`收到请求：${context.Request.RawUrl} 来自 IP：${context.Request.RemoteEndPoint.Address}`);
                const response = handleRequest(context.Request.RawUrl, context.Request.Headers["Authorization"]);
                sendResponse(context, response);
            }
        } catch (e) {
            serein.console.error(`处理请求时出现错误：${e.message}`);
        }
    }, 100);
}

// 构建响应
function sendResponse(context, response) {
    const responseBytes = Encoding.UTF8.GetBytes(response.responseBody);
    context.Response.StatusCode = response.statusCode;
    context.Response.StatusDescription = response.statusDescription;
    context.Response.ContentLength64 = responseBytes.length;
    context.Response.OutputStream.Write(responseBytes, 0, responseBytes.length);
    context.Response.Close();
}

// 请求处理逻辑
function handleRequest(rawUrl, authHeader) {
    if (!isValidAuthKey(authHeader)) {
        return createErrorResponse(401, "Unauthorized: Invalid or missing Authorization key");
    }

    if (rawUrl === '/serein/health') {
        return createSuccessResponse(200, "OK");
    }

    if (rawUrl.startsWith('/serein/start')) {
        return handleServerAction(rawUrl, "start");
    }

    if (rawUrl.startsWith('/serein/stop')) {
        return handleServerAction(rawUrl, "stop");
    }

    if (rawUrl.startsWith('/serein/terminate')) {
        return handleServerAction(rawUrl, "terminate");
    }

    return createErrorResponse(404, "Not Found");
}

// 处理服务器操作
function handleServerAction(rawUrl, action) {
    const { id, pmid, gmid, msg } = getQueryParams(rawUrl);
    if (!id) {
        return createErrorResponse(400, "Missing required parameter: id");
    }

    try {
        serein.servers[id][action]();
        return sendMessageAfterAction(id, pmid, gmid, msg, `Server ${id} ${action}ed successfully`);
    } catch (e) {
        return createErrorResponse(500, `Failed to ${action} server ${id}: ${e.message}`);
    }
}

// 发送消息
function sendMessageAfterAction(id, pmid, gmid, message, successMessage) {
    if (pmid && message) {
        try {
            serein.connection.sendPrivateMsg(pmid, message);
            successMessage += ` and private message sent to ${pmid}`;
        } catch (e) {
            return createErrorResponse(500, `Failed to send private message to user ${pmid}: ${e.message}`);
        }
    }

    if (gmid && message) {
        try {
            serein.connection.sendGroupMsg(gmid, message);
            successMessage += ` and group message sent to group ${gmid}`;
        } catch (e) {
            return createErrorResponse(500, `Failed to send group message to group ${gmid}: ${e.message}`);
        }
    }

    return createSuccessResponse(200, successMessage);
}

// 验证授权密钥
function isValidAuthKey(authHeader) {
    return authHeader && authHeader.startsWith("Bearer ") && config.auth.includes(authHeader.substring(7));
}

// 创建成功响应
function createSuccessResponse(statusCode, message) {
    return {
        statusCode,
        statusDescription: "OK",
        responseBody: JSON.stringify({ statusCode, message }),
    };
}

// 创建错误响应
function createErrorResponse(statusCode, message) {
    return {
        statusCode,
        statusDescription: statusCode === 401 ? "Unauthorized" : "Error",
        responseBody: JSON.stringify({ statusCode, message }),
    };
}

// 获取查询参数
function getQueryParams(url) {
    const query = url.split('?')[1];
    if (!query) return {};
    return Object.fromEntries(query.split('&').map(param => param.split('=').map(decodeURIComponent)));
}

**Comment by Chlna6666** [comment]
```javascript
var HttpListener = importNamespace('System.Net').HttpListener;
var Encoding = importNamespace('System.Text').Encoding;
var IO = importNamespace('System.IO');
var File = IO.File;
var Directory = IO.Directory;

if (!HttpListener.IsSupported) {
    throw new Error("当前系统不支持 HttpListener");
}

// 默认配置
let config = {
    auth: [""],
    port: 61545,
};

// 配置文件路径
const CONFIG_DIR = 'Serein/plugins/BackupJS';
const CONFIG_FILE = `${CONFIG_DIR}/config.json`;

// 生成随机密钥
function generateRandomKey(length = 12) {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    return Array.from({ length }, () => chars.charAt(Math.floor(Math.random() * chars.length))).join('');
}

// 加载或创建配置文件
function loadConfig() {
    if (Directory.Exists(CONFIG_DIR) && File.Exists(CONFIG_FILE)) {
        try {
            const loadedConfig = JSON.parse(File.ReadAllText(CONFIG_FILE));
            if (!loadedConfig.auth || !loadedConfig.auth[0]) {
                loadedConfig.auth = [generateRandomKey()];
                saveConfig(loadedConfig);
                serein.console.warn(`AuthKey 为空，已生成随机密钥：${loadedConfig.auth[0]}`);
            }
            return loadedConfig;
        } catch (e) {
            throw new Error(`读取配置文件时出现问题：${e.message}`);
        }
    } else {
        Directory.CreateDirectory(CONFIG_DIR);
        config.auth = [generateRandomKey()];
        saveConfig(config);
        serein.console.warn("配置文件不存在，已重新创建默认配置");
        serein.console.warn(`随机生成的 AuthKey 为：${config.auth[0]}`);
        return config;
    }
}

// 保存配置文件
function saveConfig(config) {
    File.WriteAllText(CONFIG_FILE, JSON.stringify(config, null, 4));
}

// 加载配置
config = loadConfig();

// 启动监听器
let listener = new HttpListener();
listener.Prefixes.Add(`http://127.0.0.1:${config.port}/serein/`);
try {
    listener.Start();
    serein.console.log(`服务已启动，正在监听 http://127.0.0.1:${config.port}/serein/`);
    startListener();
} catch (e) {
    throw new Error(`无法启动监听器：${e.message}`);
    listener.Close();
}

// 主监听逻辑
function startListener() {
    setTimeout(() => {
        try {
            while (listener.IsListening) {
                let context = listener.GetContext();
                serein.console.log(`收到请求：${context.Request.RawUrl} 来自 IP：${context.Request.RemoteEndPoint.Address}`);
                const response = handleRequest(context.Request.RawUrl, context.Request.Headers["Authorization"]);
                sendResponse(context, response);
            }
        } catch (e) {
            serein.console.error(`处理请求时出现错误：${e.message}`);
        }
    }, 100);
}

// 构建响应
function sendResponse(context, response) {
    const responseBytes = Encoding.UTF8.GetBytes(response.responseBody);
    context.Response.StatusCode = response.statusCode;
    context.Response.StatusDescription = response.statusDescription;
    context.Response.ContentLength64 = responseBytes.length;
    context.Response.OutputStream.Write(responseBytes, 0, responseBytes.length);
    context.Response.Close();
}

// 请求处理逻辑
function handleRequest(rawUrl, authHeader) {
    if (!isValidAuthKey(authHeader)) {
        return createErrorResponse(401, "Unauthorized: Invalid or missing Authorization key");
    }

    if (rawUrl === '/serein/health') {
        return createSuccessResponse(200, "OK");
    }

    if (rawUrl.startsWith('/serein/start')) {
        return handleServerAction(rawUrl, "start");
    }

    if (rawUrl.startsWith('/serein/stop')) {
        return handleServerAction(rawUrl, "stop");
    }

    if (rawUrl.startsWith('/serein/terminate')) {
        return handleServerAction(rawUrl, "terminate");
    }

    return createErrorResponse(404, "Not Found");
}

// 处理服务器操作
function handleServerAction(rawUrl, action) {
    const { id, pmid, gmid, msg } = getQueryParams(rawUrl);
    if (!id) {
        return createErrorResponse(400, "Missing required parameter: id");
    }

    try {
        serein.servers[id][action]();
        return sendMessageAfterAction(id, pmid, gmid, msg, `Server ${id} ${action}ed successfully`);
    } catch (e) {
        return createErrorResponse(500, `Failed to ${action} server ${id}: ${e.message}`);
    }
}

// 发送消息
function sendMessageAfterAction(id, pmid, gmid, message, successMessage) {
    if (pmid && message) {
        try {
            serein.connection.sendPrivateMsg(pmid, message);
            successMessage += ` and private message sent to ${pmid}`;
        } catch (e) {
            return createErrorResponse(500, `Failed to send private message to user ${pmid}: ${e.message}`);
        }
    }

    if (gmid && message) {
        try {
            serein.connection.sendGroupMsg(gmid, message);
            successMessage += ` and group message sent to group ${gmid}`;
        } catch (e) {
            return createErrorResponse(500, `Failed to send group message to group ${gmid}: ${e.message}`);
        }
    }

    return createSuccessResponse(200, successMessage);
}

// 验证授权密钥
function isValidAuthKey(authHeader) {
    return authHeader && authHeader.startsWith("Bearer ") && config.auth.includes(authHeader.substring(7));
}

// 创建成功响应
function createSuccessResponse(statusCode, message) {
    return {
        statusCode,
        statusDescription: "OK",
        responseBody: JSON.stringify({ statusCode, message }),
    };
}

// 创建错误响应
function createErrorResponse(statusCode, message) {
    return {
        statusCode,
        statusDescription: statusCode === 401 ? "Unauthorized" : "Error",
        responseBody: JSON.stringify({ statusCode, message }),
    };
}

// 获取查询参数
function getQueryParams(url) {
    const query = url.split('?')[1];
    if (!query) return {};
    return Object.fromEntries(query.split('&').map(param => param.split('=').map(decodeURIComponent)));
}

**Comment by Zaitonn** [comment]
加个这个确保在卸载的时候把这玩意释放了
```ts
serein.setListener('PluginsUnloading', ()=>{listener.Dispose();})
```

但是你的`HttpListener`用的是阻塞的方式，最好改成用[`HttpListener.BeginGetContext`](https://learn.microsoft.com/zh-cn/dotnet/api/system.net.httplistener.begingetcontext?view=net-8.0)避免无法在卸载插件的时候因线程阻塞导致无法调用插件卸载时的回调函数

你可以参考一下这个插件

https://github.com/SereinCommunity/older-extensions-gallery/blob/b079a02c8671d74026d1da523b884c7748e21e49/JS/HTTPApi/HTTPApi.js#L58-L91

**Comment by Zaitonn** [comment]
> ```ts
> serein.setListener('PluginsUnloading', ()=>{listener.Dispose();})
> ```

这个还没加到文档里面，用法和v1的差不太多，但是事件的名称和函数填充的参数有一些变化，具体的参数可以看https://github.com/SereinDev/Serein/blob/main/src/Serein.Core/Models/Plugins/Net/PluginBase.Events.cs

因为是测试版所以在发布前可能还会有破坏性的变化

**Comment by Chlna6666** [comment]
好的感谢
